'use client'; // Убедитесь, что компонент выполняется на стороне клиента

import React from 'react';
import { motion } from 'framer-motion';
import TypedTextOne from './TypedTextOnce';

const Roadmap = () => {
  return (
    <section className="py-16 px-4 rounded-xl flex flex-col z-[2]" id="roadmap">
      <h2 className="text-3xl sm:text-5xl font-semibold text-center mb-14 z-[2]"><TypedTextOne text={"Roadmap //"} /></h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3">
        {[
          {
            phase: 'Phase I (Q1 2025)',
            title: 'Public Demonstration of Efficiency',
            description: 'Launching a staking program that enables token holders to stake their tokens and earn passive income from the profits generated by an trading bot',
          },
          {
            phase: 'Phase II (Q1 2025)',
            title: 'Launch a Utility Token',
            description: 'Launching a staking program that enables token holders to stake their tokens and earn passive income from the profits generated by an trading bot',
          }, {
            phase: 'Phase III (Q1 2025)',
            title: 'Community and Revenue Sharing',
            description: 'Launching a staking program that enables token holders to stake their tokens and earn passive income from the profits generated by an trading bot',
          }, {
            phase: 'Phase IV (Q2 - Q3 2025)',
            title: 'Expanding the Ecosystem',
            description: 'Launching a staking program that enables token holders to stake their tokens and earn passive income from the profits generated by an trading bot',
          },
        ].map((phase, index) => (
          <motion.div
            key={index}
            className="bg-[#0D1327] p-6 rounded-xl shadow-lg flex flex-col justify-between  z-[2] "
            initial={{ opacity: 0, scale: 0.5 }} // Начальное состояние (невидим и уменьшен)
            whileInView={{ opacity: 1, scale: 1 }} // Анимация при появлении в области видимости
            viewport={{ once: true }} // Анимация сработает только один раз
            transition={{
              duration: 0.3,
              delay: index * 0.3, // Задержка для каждого блока
              type: "spring", // Пружинный эффект
              stiffness: 20, // Жесткость пружины
              damping: 10, // Затухание
            }}
          >
            {index % 2 ? <>
            
              <h3 className="font-semibold text-2xl mb-2">{phase.title}</h3>
              <p className='font-medium opacity-50'>{phase.description}</p>
              <p className='mt-24 font-medium opacity-50'>{phase.phase}</p>
            </> : <>
            <p className='mb-24 font-medium opacity-50'>{phase.phase}</p>
              <h3 className="font-semibold text-2xl mb-2">{phase.title}</h3>
              <p className='font-medium opacity-50'>{phase.description}</p>
              
            </> }

          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default Roadmap;