'use client'; // Убедитесь, что компонент выполняется на стороне клиента

import React from 'react';
import { motion } from 'framer-motion';
import TypedTextOne from './TypedTextOnce';
import Glow from './Glow';

const WhatIs = () => {
  // Анимация для появления блоков
  const fadeInUp = {
    hidden: { opacity: 0, y: 50 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
  };
  return (
    <section className="py-16  z-[2] flex flex-col" id="about">
      {/* Анимация для заголовка */}
      <h2 className="text-3xl sm:text-5xl font-semibold text-center mb-8  z-[2]"><TypedTextOne text={"What is APIS //"}/></h2>
      

      {/* Анимация для текста */}
      <motion.p
        className="text-xl font-medium max-w-3xl mx-auto text-center px-4 mb-10  z-[2]"
        initial={{ opacity: 0, y: 20 }} // Начальное состояние (невидим и смещен вниз)
        whileInView={{ opacity: 1, y: 0 }} // Анимация при появлении в области видимости
        viewport={{ once: true }} // Анимация сработает только один раз
        transition={{ duration: 0.8, ease: 'easeOut', delay: 0.3 }} // Задержка для текста
      >
        APIS is an innovative protocol that leverages cutting-edge <br /> technologies in machine learning, artificial intelligence, and financial <br /> analysis to create a powerful trading bot
      </motion.p>
      <div className="flex flex-col md:flex-row justify-center gap-8  z-[2]">
        {/* Первый блок */}
        <motion.div
          className="bg-[#121B37] px-8 py-16 shadow-lg rounded-2xl w-full md:w-[45%] text-start mb-6 md:mb-0"
          variants={fadeInUp}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.5 }} // Анимация сработает только один раз
        >
          <h3 className="text-2xl font-semibold mb-4">Stack</h3>
          <p className="mb-4 opacity-50">The AI-driven protocol, built on Rust, Python, TypeScript, and Deno, integrates with the ByBIT exchange to trade futures contracts and provides users with real-time trading reports via Telegram bot</p>
        </motion.div>

        {/* Второй блок */}
        <motion.div
          className="bg-[#48539080] px-8 py-16 shadow-lg rounded-2xl w-full md:w-[45%] text-start"
          variants={fadeInUp}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.5  }} // Анимация сработает только один раз
        >
          <h3 className="text-2xl font-semibold mb-4">Mission</h3>
          <p className="mb-4 opacity-50">The main goal of aiAPIS is to create a collective revenue share model in which the income generated by the trading bot is shared among the project token holders, offering passive income opportunities</p>
        </motion.div>
      </div>
    </section>
  );
};

export default WhatIs;